name: Build and Deploy Snapshot

on:
  push:
    branches:
      - master
      - "3.0"
      - "2.19"
    paths-ignore:
      - "README.md"
      - "release-notes/*"
  pull_request:
    branches:
      - master
      - "3.0"
      - "2.19"
    paths-ignore:
      - "README.md"
      - "release-notes/*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - java_version: "8"
            os: "ubuntu-22.04"
            architecture: "x64"
          - java_version: "11"
            os: "ubuntu-22.04"
            architecture: "x64"
          - java_version: "17"
            os: "ubuntu-22.04"
            architecture: "x64"
          - java_version: "21"
            os: "ubuntu-22.04"
            architecture: "x64"
          - java_version: "8"
            os: "ubuntu-22.04-ppc64le"
            architecture: "ppc64le"
          - java_version: "11"
            os: "ubuntu-22.04-ppc64le"
            architecture: "ppc64le"
          - java_version: "17"
            os: "ubuntu-22.04-ppc64le"
            architecture: "ppc64le"
          - java_version: "21"
            os: "ubuntu-22.04-ppc64le"
            architecture: "ppc64le"

    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Set up JDK
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java_version }}
          architecture: ${{ matrix.architecture }}
          cache: "maven"

      - name: Build
        run: ./mvnw -B -q -ff -ntp verify

    # - name: Extract project Maven version
    #   id: projectVersion
    #   run: echo "version=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.4.1:evaluate -DforceStdout -Dexpression=project.version -q)" >> $GITHUB_OUTPUT

    # - name: Deploy snapshot
    #   if: github.event_name != 'pull_request' && matrix.java_version == '8' && endsWith(steps.projectVersion.outputs.version, '-SNAPSHOT')
    #   env:
    #     CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
    #     CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
    #   run: ./mvnw -B -q -ff -DskipTests -ntp source:jar deploy
